### ISSUE TITLE
Problem with audeep.backend.parsers.no_metadata.NoMetadataParser

### ISSUE THREAD

**Issue by frankenjoe** [auDeep/auDeep#1]
Hi,

using `inspect` with `audeep.backend.parsers.no_metadata.NoMetadataParser` seems to crash.

Changing line 97 in `inspect.py` from:

            ("number of labels", len(parser.label_map)),

to

            ("number of labels", len(parser.label_map) if parser.label_map else 0),

solved the issue,

cheers.

**Comment by freitmi** [comment]
Fixed in master, will be part of next release. Thanks for reporting and providing a fix!
