### ISSUE TITLE
wrong with 'sh audeep_generate.sh'

### ISSUE THREAD

**Issue by LuoDQ** [auDeep/auDeep#10]
### System information
Make sure to provide all system information that may be relevant to the issue you are reporting. Some common points are:

- **Have I written custom code (as opposed to using an example script provided with auDeep)**: 
   no, use the example script.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  14.04.4
- **auDeep version (Git commit SHA / release version)**:0.9.1
- **Python version**: 3.5.4
- **Exact command to reproduce**:sh audeep_generate.sh

### Describe the problem
when I run 'sh audeep_generate.sh',  it reports lots of error and can't complete  .

### Source code / logs
when I run the spectrogram extraction part in the script:
`audeep - int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

when I run the autoencoder training part, I get:
`audeep_generate.sh: 98: [: x: unexpected operator`
`audeep_generate.sh: 102: [: b: unexpected operator`
`audeep t-rae train --input audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc --run-name audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b --tempdir audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b/tmp --num-epochs 64 --batch-size 256 --learning-rate 0.001 --keep-prob 0.8 --cell GRU --num-layers 2 --num-units 256 --bidirectional-decoder`
`[INFO] TrainTimeAutoencoder - created temporary file audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b/tmp/compare18-atypical-affect-0.08-0.04-128-30.nc-0 for data set audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc
[INFO] audeep.backend.data.data_set - loading data set from audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc
[ERROR] audeep - 'filename'`

when I run the feature generation part, I get:
`audeep t-rae generate --model-dir audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b/logs --input audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc --output audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b/representations.nc`
`[INFO] audeep.backend.data.data_set - loading data set from audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc
[ERROR] audeep - 'filename'`

then, when I run the feature fusion part, I get:
`audeep fuse --input audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128*/*/representations.nc --output audeep_workspace/output/compare18-atypical-affect-fused/representations.nc`
`[ERROR] audeep - failed to open data set at audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128*/*/representations.nc`

finally, when I run the feature export part, I get errors like this:
`[ERROR] audeep - failed to open data set at audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b/representations.nc
cp: 无法获取"audeep_workspace/arff/partitions/train/ComParE2018_AtypicalAffect.auDeep-30.arff" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"audeep_workspace/arff/partitions/devel/ComParE2018_AtypicalAffect.auDeep-30.arff" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"audeep_workspace/arff/partitions/test/ComParE2018_AtypicalAffect.auDeep-30.arff" 的文件状态(stat): 没有那个文件或目录
audeep export --input audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-45/t-2x256-x-b/representations.nc --format ARFF --labels-last --output audeep_workspace/arff/partitions --name ComParE2018_AtypicalAffect.auDeep-45`

**Comment by signalogy** [comment]
You might want to add --debug to see the errors more in detail. 

From your description, it looks like it has something to do with xarray version (as described in #9). You try to downgrade xarray 0.10.0.
