### ISSUE TITLE
[ERROR] audeep - module 'tensorflow' has no attribute 'logging'

### ISSUE THREAD

**Issue by vijaysumaravi** [auDeep/auDeep#16]
### System information
Make sure to provide all system information that may be relevant to the issue you are reporting. Some common points are:

- **Have I written custom code (as opposed to using an example script provided with auDeep)**:
Not added anything
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu  16.04
- **auDeep version (Git commit SHA / release version)**: audeep 0.9.1
- **Python version**:  Python 3.5.2
- **Exact command to reproduce**:  audeep inspect raw --basedir ESC-10 

### Describe the problem
Describe the problem clearly here. 
When I run the above code or when I just execute sh audeep_generate.sh I get an Error message that says [ERROR] audeep - module 'tensorflow' has no attribute 'logging'. Might be a trivial issue, bot not able to figure out what. Any help is appreciated!  Thanks! 

### Source code / logs
sh audeep_generate.sh 
audeep preprocess --parser audeep.audeep.backend.parsers.compare18_atypical_affect.Compare18AtypicalAffectParser --basedir ../wav --output /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc --window-width 0.08 --window-overlap 0.04 --fixed-length 5 --center-fixed --clip-below -30 --mel-spectrum 128

[ERROR] audeep - module 'tensorflow' has no attribute 'logging'
audeep preprocess --parser audeep.audeep.backend.parsers.compare18_atypical_affect.Compare18AtypicalAffectParser --basedir ../wav --output /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-45.nc --window-width 0.08 --window-overlap 0.04 --fixed-length 5 --center-fixed --clip-below -45 --mel-spectrum 128

[ERROR] audeep - module 'tensorflow' has no attribute 'logging'
audeep preprocess --parser audeep.audeep.backend.parsers.compare18_atypical_affect.Compare18AtypicalAffectParser --basedir ../wav --output /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-60.nc --window-width 0.08 --window-overlap 0.04 --fixed-length 5 --center-fixed --clip-below -60 --mel-spectrum 128

[ERROR] audeep - module 'tensorflow' has no attribute 'logging'
audeep preprocess --parser audeep.audeep.backend.parsers.compare18_atypical_affect.Compare18AtypicalAffectParser --basedir ../wav --output /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-75.nc --window-width 0.08 --window-overlap 0.04 --fixed-length 5 --center-fixed --clip-below -75 --mel-spectrum 128

[ERROR] audeep - module 'tensorflow' has no attribute 'logging'
audeep_generate.sh: 98: [: x: unexpected operator
audeep_generate.sh: 102: [: b: unexpected operator
audeep t-rae train --input /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/input/spectrograms/compare18-atypical-affect-0.08-0.04-128-30.nc --run-name /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b --tempdir /media/amber/D/Databases/ComparE/data/ComParE2018_AtypicalAffect/baseline_audeep/audeep_workspace/output/compare18-atypical-affect-0.08-0.04-128-30/t-2x256-x-b/tmp --num-epochs 64 --batch-size 256 --learning-rate 0.001 --keep-prob 0.8 --cell GRU --num-layers 2 --num-units 256

**Comment by freitmi** [comment]
I suspect that you have the wrong Tensorflow version (auDeep needs exactly 1.1.0). You can display your Tensorflow version with the following command:
```
python3 -c 'import tensorflow as tf; print(tf.__version__)'
```

**Comment by vijaysumaravi** [comment]
@freitmi Thanks!
