### ISSUE TITLE
Compare2018 script issues

### ISSUE THREAD

**Issue by signalogy** [auDeep/auDeep#2]
Hi,
While I was trying to run the auDeep baseline in the compare18, it stops with a lot of errors. 

As I track them down, the initial error is from t-rae training procedure as following.  Can you take a look at the error as the error message is not too clear for me.

`audeep t-rae train --input audeep_workspace/input/spectrograms/compare18-crying-0.08-0.04-128-30.nc --run-name audeep_workspace/output/compare18-crying-0.08-0.04-128-30/t-2x256-x-b --tempdir audeep_workspace/output/compare18-crying-0.08-0.04-128-30/t-2x256-x-b/tmp --num-epochs 32 --batch-size 512 --learning-rate 0.001 --keep-prob 0.8 --cell GRU --num-layers 2 --num-units 256 --bidirectional-decoder 
[ERROR] audeep - Graph contains unbound inputs: $unbound_inputs_inputs,$unbound_inputs_inputs,$unbound_inputs_inputs,$unbound_inputs_inputs,$unbound_inputs_inputs,$unbound_inputs_inputs,$unbound_inputs_encoder_noise,$unbound_inputs_inputs,$unbound_inputs_inputs,$unbound_inputs_keep_prob,$unbound_inputs_inputs,$unbound_inputs_decoder_feed_previous_prob,$unbound_inputs_keep_prob,$unbound_inputs_keep_prob,$unbound_inputs_keep_prob,$unbound_inputs_keep_prob,$unbound_inputs_keep_prob,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate,$unbound_inputs_learning_rate. Must provide these inputs through input_map.`  

Running on: Ubuntu 16.4.3 LTS and Tensorflow 1.1.0

**Comment by freitmi** [comment]
Hi there,

This very much looks like its caused by a known bug in Tensorflow (https://github.com/tensorflow/tensorflow/issues/10250). We ship a patch which fixes this bug with auDeep (in the patches subfolder). Did you apply this patch as described in the installation instructions?

Cheers

**Comment by signalogy** [comment]
Thanks and sorry. I overlooked the instruction. After the patch, it works as it should be.
