### ISSUE TITLE
Not matching distribution found for tensorflow=1.1.0 (from auDeep 0.9.1)

### ISSUE THREAD

**Issue by erituert** [auDeep/auDeep#23]
### System information
- **OS Platform and Distribution**: Windows 7 Professional
- **auDeep version (Git commit SHA / release version)**: auDeep 0.9.1
- **Python version**: Python 3.6.5, Anaconda3 5.2.0
- **Exact command to reproduce**: pip install ./auDeep

### Describe the problem
I'm following the exact steps in the README to install auDeep, but when writting: 
`pip install ./auDeep`

I get the following error:

> Collecting tensorflow==1.1.0 (from auDeep==0.9.1)
>   Could not find a version that satisfies the requirement tensorflow==1.1.0 (fro
> m auDeep==0.9.1) (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3
> .0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0
> rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.
> 0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.11.0rc0,
>  1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc
> 0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 2.0.0a0)
> No matching distribution found for tensorflow==1.1.0 (from auDeep==0.9.1)

I have read that tensorflow 1.1.0 is no longer supported by pip, could that be the problem?

As a temporal solution, I tried downloading tensorflow 1.1.0 .whl for windows, but the only file I could find was for Python 3.5, so I installed Python 3.5 and tried manually installing the tensorflow .whl. And then another problem arised, when writting the same auDeep installation command, the output was:

> yield inside async function python

And after checking this, I found out that 'yield' for asynchronous generators could only be used after Python 3.6.

Does anyone have a solution for this or has faced a similar problem?

Thanks in advance

**Comment by mauricege** [comment]
You are completely right that version 1.1 is no longer available through pip preventing auDeep from installing correctly. I created a new branch which bumps tensorflow to the most recent version (1.13).
I only tested it with the tutorial from the README so far.

Let me know if it resolves your issue!

**Comment by erituert** [comment]
Thank you! It does solve that issue, although I get another error now.

After:

`pip install ./auDeep`

I get the following message: 

> Successfully installed PrettyTable-0.7.2 PyYAML-5.1 absl-py-0.7.1 astor-0.7.1 at trs-19.1.0 auDeep-0.9.2 cffi-1.12.2 cftime-1.0.3.4 cliff-2.14.1 cmd2-0.9.11 colo rama-0.4.1 cycler-0.10.0 gast-0.2.2 grpcio-1.19.0 h5py-2.9.0 keras-applications- 1.0.7 keras-preprocessing-1.0.9 kiwisolver-1.0.1 liac-arff-2.4.0 markdown-3.1 ma tplotlib-3.0.3 mock-2.0.0 netCDF4-1.5.0.1 numpy-1.16.2 pandas-0.24.2 pbr-5.1.3 p rotobuf-3.7.1 pycparser-2.19 pyparsing-2.4.0 pyperclip-1.7.0 pyreadline-2.1 pyso undfile-0.9.0.post1 python-dateutil-2.8.0 pytz-2019.1 scikit-learn-0.20.3 scipy- 1.2.1 six-1.12.0 sklearn-0.0 stevedore-1.30.1 tensorboard-1.13.1 tensorflow-1.13 .1 tensorflow-estimator-1.13.0 termcolor-1.1.0 wcwidth-0.1.7 werkzeug-0.15.2 xar ray-0.10.0 


But there is another problem. I thought no patch for Tensorflow would be necessary as the version is 1.13.1 instead of 1.1.0, but when trying to check auDeep version:
`auDeep --version`

The following stack trace appears:

> [ERROR] audeep - Traceback (most recent call last):
>   File "c:\audeep_virtualenv\lib\site-packages\tensorflow\python\pywrap_tensorfl
> ow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "c:\audeep_virtualenv\lib\site-packages\tensorflow\python\pywrap_tensorfl
> ow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "c:\audeep_virtualenv\lib\site-packages\tensorflow\python\pywrap_tensorfl
> ow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
> ion)
>   File "c:\audeep_virtualenv\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "c:\audeep_virtualenv\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed with error code -1073741795
> Failed to load the native TensorFlow runtime.
> See https://www.tensorflow.org/install/errors
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

I thought it could be due to the necessary patch for Tensorflow within the virtualenv, so I installed `cygwin `and its `patch `package and when writting on cygwin:


`$ patch ./audeep_virtualenv/Lib/site-ackages/tensorflow/python/framework/meta_graph.py ./auDeep/patches/fix_import_bug.patch`

I get the following message:

> patching file ./audeep_virtualenv/Lib/site-packages/tensorflow/python/framework/meta_graph.py
> Hunk #1 FAILED at 472 (different line endings).
> 1 out of 1 hunk FAILED -- saving rejects to file ./audeep_virtualenv/Lib/site-packages/tensorflow/python/framework/meta_graph.py.rej

So I guess auDeep is not completely installed, any ideas about how to solve the issue?

Thanks again in advance!

**Comment by mauricege** [comment]
Hey again!

Can you import tensorflow in your audeep virtualenv? I.e., `python -c "import tensorflow as tf"`. If this returns the same error, can you try try installing tensorflow==1.13.1 into a fresh virtual environment? 

The error does not seem to be related to the patch.

**Comment by erituert** [comment]
Got the same error, **but** I've been able to solve it!

It looked like the error with tensorflow had occured to many other people, and some said it had to do with the 'protobuf' version, so here is what i did:

`virtualenv -p python3 new_virtualenv`
`.\new_virtualenv\Scripts\activate.bat`
`pip install protobuf`
`pip install tensorflow==1.13.1`
`pip show protobuf ` (worked correctly, v. 3.7.1)
`pip show tensorflow` (worked correctly, v 1.13.1)
`pip install .\auDeep`

Then `auDeep --version` showed the following message:

> audeep 0.9.1  Copyright (C) 2017-2018 Michael Freitag, Shahin Amiriparian, Serge
> y Pugachevskiy, Nicholas Cummins, Bjoern Schuller
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.

Seems it has been installed correctly! I'm going to start working with auDeep asap.
Thanks for everything!

**Comment by erituert** [comment]
Hi again! I've stated following the steps listed on your tutorial and got stuck at the very beggining.

Even though the commands
```
(audeep_virtualenv) C:\Users\user\Desktop\Datos\auDeepVirtEnv>audeep inspect
 raw --basedir ESC-10
[ERROR] audeep - Traceback (most recent call last):
  File "c:\users\user\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\user\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\user\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_imp
ort_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "c:\users\user\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\imp.
py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\user\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\imp.
py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by erituert** [comment]
Hi again! I've started following the steps listed on your tutorial and got stuck again at the very beggining.

When using commands `pip show tensorflow` or `audeep --version`, both work correctly showing tensorflow 1.13.1 and audeep 0.9.1 (shouldn't it be here 0.9.2?) versions. But when I go on with the ESC-10 database processing, I get a problem with tensorflow.

```
(audeep_virtualenv) C:\Users\erituert\Desktop\Datos\auDeepVirtEnv>audeep inspect
 raw --basedir ESC-10
[ERROR] audeep - Traceback (most recent call last):
  File "c:\users\erituert\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\erituert\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\erituert\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_imp
ort_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "c:\users\erituert\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\imp.
py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\erituert\desktop\datos\audeepvirtenv\audeep_virtualenv\lib\imp.
py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

I've tried creating several new virtual environments and keep getting the same error over and over. Some people suggest the use of protobuf 3.6.0, but that version is not compatible with tensorflow 1.13.1, and I haven't found any solutions yet. I'm trying installing auDeep on Linux to see if Windows is the problem, but I would prefer using it on Windows.

Thanks again!






**EDIT:** When creating a new virtual environment and installing tensorflow 1.13.1, leads me to the same error.
```
(base) C:\Users\erituert\Desktop\Datos\auDeepVirtEnv>virtualenv -p python audeep
_virtualenv
[...]
done.

(base) C:\Users\erituert\Desktop\Datos\auDeepVirtEnv>.\audeep_virtualenv\Scripts
\activate.bat

(audeep_virtualenv) (base) C:\Users\erituert\Desktop\Datos\auDeepVirtEnv>pip ins
tall tensorflow==1.13.1
Collecting tensorflow==1.13.1
[...]
Successfully installed absl-py-0.7.1 astor-0.7.1 gast-0.2.2 grpcio-1.20.1 h5py-2
.9.0 keras-applications-1.0.7 keras-preprocessing-1.0.9 markdown-3.1 mock-2.0.0
numpy-1.16.3 pbr-5.2.0 tensorboard-1.13.1 tensorflow-1.13.1 tensorflow-estimator
-1.13.0 termcolor-1.1.0 werkzeug-0.15.2

(audeep_virtualenv) (base) C:\Users\erituert\Desktop\Datos\auDeepVirtEnv>python
-c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_imp
ort_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\imp.
py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\imp.
py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\site
-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_imp
ort_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\imp.
py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\erituert\Desktop\Datos\auDeepVirtEnv\audeep_virtualenv\lib\imp.
py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(audeep_virtualenv) (base) C:\Users\erituert\Desktop\Datos\auDeepVirtEnv>
```

Happens with tensorflow versions 1.12, 1.13 and new one 2.0.0a. 


**FIXED**: When forcing the installation of tensorflow version 1.2.0, the problem seems fixed and the tutorial (until extracting the metadata of the audio files) works! Steps:

```
virtualenv -p python3 audeep_virtualenv
.\audeep_virtualenv\Scripts\activate.bat
pip install tensorflow=1.2.0
pip3 install ./auDeep
```
