### ISSUE TITLE
Couldn't run first example

### ISSUE THREAD

**Issue by felipebravom** [auDeep/auDeep#3]
Hi,
I successfully installed auDeep by following the instructions. However, when tried to run the first example command I got the following error:

(audeep_virtualenv) fbravoma@ml-20:~$ audeep inspect raw --basedir ESC-10
[INFO] MetaParser - using ESCParser to parse dataset at ESC-10
[INFO] InspectRaw - reading audio file information
[ERROR] audeep - zero-size array to reduction operation minimum which has no identity

Any ideas of what is happening?
Thanks.

**Comment by freitmi** [comment]
Hi there,

it appears as if the ESC-10 Git repository has been merged with the [ESC-50](https://github.com/karoldvl/ESC-50) repository, and doesn't contain audio files anymore. We will update the documentation accordingly. 

In the meantime, you should be able to follow through the example using the ESC-50 data set, or by checking out an older version of the ESC-10 data set (e.g. commit [553c8f1](https://github.com/karoldvl/ESC-10/commit/553c8f1743b9dba6b282e1323c3ca8fa76923448)).

Cheers

**Comment by felipebravom** [comment]
Thanks!
