### ISSUE TITLE
Model documentation

### ISSUE THREAD

**Issue by simplelife2010** [auDeep/auDeep#31]
Hi,

I found auDeep by accident and like it a lot so far. Is there any documentation on the model architectures beside the TensorBoard graphs?

Kind regards
Bruno

**Comment by mauricege** [comment]
Hi,

happy to hear you like auDeep! For details on the model architectures, you can check out our research paper:

> S. Amiriparian, M. Freitag, N. Cummins, and B. Schuller. Sequence to sequence autoencoders for unsupervised representation learning from audio, Proceedings of the Detection and Classification of Acoustic Scenes and Events 2017 Workshop, pp. 17-21, 2017

The exact architecture of a specific model depends on the configuration arguments you pass to the tool in the pre-processing and autoencoder training steps. Here, it is indeed easiest to consult the TensorBoard graphs.

Best wishes,
Maurice

**Comment by simplelife2010** [comment]
Thank you Maurice,

I will check the paper and the code as well. I think the code is well organized, so I could easily write a custom parser.

One more question. Would it be possible to use a trained model as a decoder without too much effort?

**Comment by mauricege** [comment]
> One more question. Would it be possible to use a trained model as a decoder without too much effort?

Unfortunately, this is not possible without majorly rewriting large parts of the project. Are you looking at a specific use-case that would require this functionality?

**Comment by simplelife2010** [comment]
Not really, I was just thinking about some experiments to learn how autoencoders deal with sound.

For my main use case - audio based anomaly detection - I do not need this.

So this is no issue at all. Thanks

**Comment by simplelife2010** [comment]
If you want, you can close this issue.
