### ISSUE TITLE
Cannot recognize 'preprocess' as audeep command

### ISSUE THREAD

**Issue by zxz003** [auDeep/auDeep#37]
### System information

- **OS Platform and Distribution: Linux Ubuntu 20.04:
- ** auDeep version: 0.9.5 
- **Python version:  3.7.5
- **Exact command to reproduce**: audeep preprocess

### Problem Description
I followed the installation procedure to install the audeep in virtual environment, then I ran "audeep --version" it returns me the correct version numbers and copyright info. However, when I try to run the "audeep preprocess" it returns me "audeep: 'preprocess' is not an audeep command. See 'audeep --help'."

**Comment by mauricege** [comment]
Hi,

this should be fixed with the latest merge and also version 0.9.6a1 on pypi. I deleted the faulty (0.9.5) version from there.

**Comment by zxz003** [comment]
> Hi,
> 
> this should be fixed with the latest merge and also version 0.9.6a1 on pypi. I deleted the faulty (0.9.5) version from there.

Thanks. I reinstalled it and everything works fine now.
