### ISSUE TITLE
'audeep - specified parser is unable to parse data set at ESC-10'

### ISSUE THREAD

**Issue by byuns9334** [auDeep/auDeep#4]
I download all requirements and tried to run 'audeep inpsect raw --basedir ESC-10' but I get this error message: 'audeep - specified parser is unable to parse data set at ESC-10' .

I already did git pull: https://github.com/auDeep/auDeep  .

What more can I try to resolve this problem?

**Comment by signalogy** [comment]
This should be related to #3

**Comment by freitmi** [comment]
I suspect the same. You could also try to run the command with the --debug and --verbose flags and provide a link to a Pastebin here. That should help in nailing down the problem.

**Comment by freitmi** [comment]
Closing due to prolongued inactivity. If this is still an issue, please reopen.

**Comment by KimiaMohsenian** [comment]
Hello!
I also have the same issue, I use ESC-50 dataset and get the following error:
   [ERROR] audeep - specified parser is unable to parse data set at ESC-50

And when I run the command with --verbose flag, this is what I get:
 [DEBUG] audeep - initializing app
 [DEBUG] audeep - prepare_to_run_command InspectRaw
 [DEBUG] PartitionedParser - cannot parse: there has to be at least one partition directory
 [DEBUG] CrossValidatedParser - cannot parse: need at least two fold directories
 [DEBUG] ESCParser - cannot parse: class directory audio does not match expected pattern 'DDD - *'
 [DEBUG] UrbanSound8KParser - cannot parse: metadata file at ESC-50/metadata/UrbanSound8K.csv missing
 [ERROR] audeep - specified parser is unable to parse data set at ESC-50
 [DEBUG] audeep - clean_up InspectRaw
