### ISSUE TITLE
Compare2018 - SAS&AtypicalAffect Parsers Problem

### ISSUE THREAD

**Issue by aliyesilkanat** [auDeep/auDeep#6]
While I am trying AuDeep baseline scripts for Sas and Atypical Affect parts of Compare2018, I faced with parser problem.

On line 112 

>             label_nominal = metadata.loc[metadata["file_name"] == file.name]["label"]

"label" gives key error for Atypical Affect script,
and I think it should be 

>             label_nominal = metadata.loc[metadata["file_name"] == file.name]["emotion"]

Same change should also be done on Sas script. as "Valence".

In conclusion, "label" key values should be replaced with the column titles on the TSV files.

**Comment by freitmi** [comment]
Hi there,

thanks alot for reporting this bug, and for providing a fix! The issue has been forwarded to a colleague, who will attend to the pull request.

Cheers
